Run sbt in batch mode from make and scripts (#2724)
This prevents sbt from auto-starting the server, which sometimes leads to a race
between different sbt processes run in parallel from make (e.g. when using cncluster)
and one of them stopping and asking for input:

```
[info] waiting for lock on /home/claudio/.sbt/boot/sbt.boot.lock to be available...
sbt thinks that server is already booting because of this exception:
sbt.internal.ServerAlreadyBootingException: java.io.IOException: org.scalasbt.ipcsocket.NativeErrorException: [98] Address already in use
...
Create a new server? y/n (default y)
```