Always expose sv runbook cometbft port (#1198)
* Always expose sv runbook cometbft port

fixes https://github.com/DACH-NY/cn-test-failures/issues/4702

[static]

Probably could be more clever here but doesn't seem worth the
complexity and potential breakage.

Signed-off-by: Moritz Kiefer <moritz.kiefer@purelyfunctional.org>

* Add missing dependency on splice-pulumi-common-sv

[static]

I hope this makes the pulumi operator happy again and fixes this

```
src/istio.ts(4,52): error TS2307: Cannot find module
'splice-pulumi-common-sv' or its corresponding type declarations.
```

Signed-off-by: Moritz Kiefer <moritz.kiefer@purelyfunctional.org>

* fmt

[static]

Signed-off-by: Moritz Kiefer <moritz.kiefer@purelyfunctional.org>

---------

Signed-off-by: Moritz Kiefer <moritz.kiefer@purelyfunctional.org>
Co-authored-by: Moritz Kiefer <moritz.kiefer@purelyfunctional.org>