Add missing dependency on splice-pulumi-common-sv (#1196)
[static]

I hope this makes the pulumi operator happy again and fixes this

```
src/istio.ts(4,52): error TS2307: Cannot find module
'splice-pulumi-common-sv' or its corresponding type declarations.
```

Signed-off-by: Moritz Kiefer <moritz.kiefer@purelyfunctional.org>
Co-authored-by: Moritz Kiefer <moritz.kiefer@purelyfunctional.org>