revert #1611 daml-sdk path change on use_enterprise=true branch [static]
#1611 broke on my Mac with enterprise enabled as follows

direnv: using flake_subdir
direnv: ([/opt/homebrew/bin/direnv export bash]) is taking a while to execute. Use CTRL-C to give up.
error:
       … while calling the 'derivationStrict' builtin

         at /builtin/derivation.nix:9:12: (source not available)

       … while evaluating derivation 'nix-shell'
         whose name attribute is located at /nix/store/sxxcxacn2y3xvgshjm06488n2cxlj4mi-source/pkgs/stdenv/generic/make-derivation.nix:375:7

       … while evaluating attribute 'nativeBuildInputs' of derivation 'nix-shell'

         at /nix/store/sxxcxacn2y3xvgshjm06488n2cxlj4mi-source/pkgs/stdenv/generic/make-derivation.nix:419:7:

          418|       depsBuildBuild              = elemAt (elemAt dependencies 0) 0;
          419|       nativeBuildInputs           = elemAt (elemAt dependencies 0) 1;
             |       ^
          420|       depsBuildTarget             = elemAt (elemAt dependencies 0) 2;

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: unable to download 'https://digitalasset.jfrog.io/artifactory/assembly/daml/3.3.0-snapshot.20250415.13756.0.vafc5c867/daml-sdk-3.3.0-snapshot.20250415.13756.0.vafc5c867-macos-x86_64.tar.gz': HTTP error 404

       response body:

       {
         "errors" : [ {
           "status" : 404,
           "message" : "File not found.; Path: 'assembly:daml/3.3.0-snapshot.20250415.13756.0.vafc5c867/daml-sdk-3.3.0-snapshot.20250415.13756.0.vafc5c867-macos-x86_64.tar.gz'"
         } ]
       }

Signed-off-by: Stephen Compall <stephen.compall@digitalasset.com>