multiple splitwell installs in UI (#4724)
* hide in-flight groups

* disable "Request to Join Group" button when Group Invite is "obviously" invalid

* pick leftmost instead of preferred domain

- because tests don't connect the preferred domain, ever, until it's too
  late

* do *not* remove directory dar

fails in test if you do not include it:

SplitwellUpgradeFrontendIntegrationTest:
 *** ABORTED ***
  java.lang.IllegalStateException: Condition never became true within 2 minutes
  at com.digitalasset.canton.console.ConsoleMacros$utils$.retry_until_true(ConsoleMacros.scala:108)
  at com.daml.network.console.HttpCNNodeAppReference.waitForInitialization(CNNodeInstanceReference.scala:180)
  at com.daml.network.console.HttpCNNodeAppReference.waitForInitialization$(CNNodeInstanceReference.scala:175)
  at com.daml.network.console.ValidatorAppReference.waitForInitialization(ValidatorAppReference.scala:18)

* do *not* remove pre-setup line

-        CNNodeEnvironmentDefinition.simpleTopology(this.getClass.getSimpleName).setup(env)

fails in test if you do not include it:

SplitwellUpgradeFrontendIntegrationTest:
 *** ABORTED ***
  java.lang.IllegalStateException: Condition never became true within 2 minutes
  at com.digitalasset.canton.console.ConsoleMacros$utils$.retry_until_true(ConsoleMacros.scala:108)
  at com.daml.network.console.HttpCNNodeAppReference.waitForInitialization(CNNodeInstanceReference.scala:180)
  at com.daml.network.console.HttpCNNodeAppReference.waitForInitialization$(CNNodeInstanceReference.scala:175)
  at com.daml.network.console.ValidatorAppReference.waitForInitialization(ValidatorAppReference.scala:18)